export const enum FridgeDisplayState {
  FRIDGE_DISPLAY_PAIR_TEXT = 0,

  FRIDGE_DISPLAY_IN_TEMP_1,
  FRIDGE_DISPLAY_OUT_TEMP_1,
  FRIDGE_DISPLAY_COOLER_TEMP
}


export const enum FridgePowerMode {
  FRIDGE_OFF_POWER = 0,
  FRIDGE_MAX_POWER,
  FRIDGE_NORMAL_POWER,
  FRIDGE_ECO_POWER,
  FRIDGE_PAUSED
}
